# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/1440x1440/AppCover.qml) \
        $$quote($$BASEDIR/assets/720x720/AppCover.qml) \
        $$quote($$BASEDIR/assets/AboutPage.qml) \
        $$quote($$BASEDIR/assets/AccountManagePage.qml) \
        $$quote($$BASEDIR/assets/AppCover.qml) \
        $$quote($$BASEDIR/assets/ArtistDetailPage.qml) \
        $$quote($$BASEDIR/assets/ArtistListItem.qml) \
        $$quote($$BASEDIR/assets/ArtistsPage.qml) \
        $$quote($$BASEDIR/assets/BarcodeLoginPage.qml) \
        $$quote($$BASEDIR/assets/CommentsPage.qml) \
        $$quote($$BASEDIR/assets/DebugPage.qml) \
        $$quote($$BASEDIR/assets/LoginPage.qml) \
        $$quote($$BASEDIR/assets/MvGridItem.qml) \
        $$quote($$BASEDIR/assets/MvPlayerPage.qml) \
        $$quote($$BASEDIR/assets/NowPlayingBar.qml) \
        $$quote($$BASEDIR/assets/NowPlayingPage.qml) \
        $$quote($$BASEDIR/assets/PlayerBar.qml) \
        $$quote($$BASEDIR/assets/PlaylistListItem.qml) \
        $$quote($$BASEDIR/assets/PlaylistPage.qml) \
        $$quote($$BASEDIR/assets/ProgressBar.qml) \
        $$quote($$BASEDIR/assets/PropertiesPage.qml) \
        $$quote($$BASEDIR/assets/QueuePage.qml) \
        $$quote($$BASEDIR/assets/SearchPage.qml) \
        $$quote($$BASEDIR/assets/SettingsPage.qml) \
        $$quote($$BASEDIR/assets/SongListItem.qml) \
        $$quote($$BASEDIR/assets/UserDetailPage.qml) \
        $$quote($$BASEDIR/assets/icons/GridIconVideo.png) \
        $$quote($$BASEDIR/assets/icons/ca_recent_contacts.png) \
        $$quote($$BASEDIR/assets/icons/cs_nc_no_contacts.png) \
        $$quote($$BASEDIR/assets/icons/ic_add.png) \
        $$quote($$BASEDIR/assets/icons/ic_add_contact.png) \
        $$quote($$BASEDIR/assets/icons/ic_add_to_play_next.png) \
        $$quote($$BASEDIR/assets/icons/ic_browser.png) \
        $$quote($$BASEDIR/assets/icons/ic_calendar_day.png) \
        $$quote($$BASEDIR/assets/icons/ic_chat_multiperson.png) \
        $$quote($$BASEDIR/assets/icons/ic_connections.png) \
        $$quote($$BASEDIR/assets/icons/ic_contact.png) \
        $$quote($$BASEDIR/assets/icons/ic_copy.png) \
        $$quote($$BASEDIR/assets/icons/ic_delete.png) \
        $$quote($$BASEDIR/assets/icons/ic_favorite.png) \
        $$quote($$BASEDIR/assets/icons/ic_groups_white.png) \
        $$quote($$BASEDIR/assets/icons/ic_help.png) \
        $$quote($$BASEDIR/assets/icons/ic_info.png) \
        $$quote($$BASEDIR/assets/icons/ic_link_contacts.png) \
        $$quote($$BASEDIR/assets/icons/ic_media_next.png) \
        $$quote($$BASEDIR/assets/icons/ic_media_previous.png) \
        $$quote($$BASEDIR/assets/icons/ic_music.png) \
        $$quote($$BASEDIR/assets/icons/ic_music_library.png) \
        $$quote($$BASEDIR/assets/icons/ic_myworld.png) \
        $$quote($$BASEDIR/assets/icons/ic_open.png) \
        $$quote($$BASEDIR/assets/icons/ic_open_contacts.png) \
        $$quote($$BASEDIR/assets/icons/ic_pause.png) \
        $$quote($$BASEDIR/assets/icons/ic_play.png) \
        $$quote($$BASEDIR/assets/icons/ic_play_on.png) \
        $$quote($$BASEDIR/assets/icons/ic_playlist_audio.png) \
        $$quote($$BASEDIR/assets/icons/ic_properties.png) \
        $$quote($$BASEDIR/assets/icons/ic_reload.png) \
        $$quote($$BASEDIR/assets/icons/ic_remove_friend.png) \
        $$quote($$BASEDIR/assets/icons/ic_repeat.png) \
        $$quote($$BASEDIR/assets/icons/ic_repeat_active.png) \
        $$quote($$BASEDIR/assets/icons/ic_repeat_focus.png) \
        $$quote($$BASEDIR/assets/icons/ic_repeat_one_active.png) \
        $$quote($$BASEDIR/assets/icons/ic_repeat_one_focus.png) \
        $$quote($$BASEDIR/assets/icons/ic_review_add.png) \
        $$quote($$BASEDIR/assets/icons/ic_scan_barcode.png) \
        $$quote($$BASEDIR/assets/icons/ic_search.png) \
        $$quote($$BASEDIR/assets/icons/ic_share.png) \
        $$quote($$BASEDIR/assets/icons/ic_shuffle_all.png) \
        $$quote($$BASEDIR/assets/icons/ic_shuffle_all_active.png) \
        $$quote($$BASEDIR/assets/icons/ic_shuffle_all_focus.png) \
        $$quote($$BASEDIR/assets/icons/icon.png) \
        $$quote($$BASEDIR/assets/icons/placeholder image.png) \
        $$quote($$BASEDIR/assets/images/avatar_bright.png) \
        $$quote($$BASEDIR/assets/images/ic_default.png) \
        $$quote($$BASEDIR/assets/images/placeholder.png) \
        $$quote($$BASEDIR/assets/main.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/MusicController.cpp) \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/nm/api/NmApi.cpp) \
        $$quote($$BASEDIR/src/nm/model/NmItems.cpp) \
        $$quote($$BASEDIR/src/nm/model/NmParsers.cpp) \
        $$quote($$BASEDIR/src/nm/net/NmCookieStore.cpp) \
        $$quote($$BASEDIR/src/nm/net/NmHttpClient.cpp) \
        $$quote($$BASEDIR/src/nm/session/NmSession.cpp) \
        $$quote($$BASEDIR/src/nm/util/NmAudioCache.cpp) \
        $$quote($$BASEDIR/src/nm/util/NmImageCache.cpp) \
        $$quote($$BASEDIR/src/nm/util/NmJson.cpp) \
        $$quote($$BASEDIR/src/nm/util/NmQrCode.cpp) \
        $$quote($$BASEDIR/src/nm/util/NmString.cpp) \
        $$quote($$BASEDIR/src/nm/util/qrcodegen/qrcodegen.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/MusicController.hpp) \
        $$quote($$BASEDIR/src/applicationui.hpp) \
        $$quote($$BASEDIR/src/nm/api/NmApi.hpp) \
        $$quote($$BASEDIR/src/nm/model/NmItems.hpp) \
        $$quote($$BASEDIR/src/nm/model/NmParsers.hpp) \
        $$quote($$BASEDIR/src/nm/net/NmCookieStore.hpp) \
        $$quote($$BASEDIR/src/nm/net/NmHttpClient.hpp) \
        $$quote($$BASEDIR/src/nm/session/NmSession.hpp) \
        $$quote($$BASEDIR/src/nm/util/NmAudioCache.hpp) \
        $$quote($$BASEDIR/src/nm/util/NmImageCache.hpp) \
        $$quote($$BASEDIR/src/nm/util/NmJson.hpp) \
        $$quote($$BASEDIR/src/nm/util/NmQrCode.hpp) \
        $$quote($$BASEDIR/src/nm/util/NmString.hpp) \
        $$quote($$BASEDIR/src/nm/util/NmTr.hpp) \
        $$quote($$BASEDIR/src/nm/util/qrcodegen/qrcodegen.h)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/nm/*.c) \
        $$quote($$BASEDIR/../src/nm/*.c++) \
        $$quote($$BASEDIR/../src/nm/*.cc) \
        $$quote($$BASEDIR/../src/nm/*.cpp) \
        $$quote($$BASEDIR/../src/nm/*.cxx) \
        $$quote($$BASEDIR/../src/nm/api/*.c) \
        $$quote($$BASEDIR/../src/nm/api/*.c++) \
        $$quote($$BASEDIR/../src/nm/api/*.cc) \
        $$quote($$BASEDIR/../src/nm/api/*.cpp) \
        $$quote($$BASEDIR/../src/nm/api/*.cxx) \
        $$quote($$BASEDIR/../src/nm/model/*.c) \
        $$quote($$BASEDIR/../src/nm/model/*.c++) \
        $$quote($$BASEDIR/../src/nm/model/*.cc) \
        $$quote($$BASEDIR/../src/nm/model/*.cpp) \
        $$quote($$BASEDIR/../src/nm/model/*.cxx) \
        $$quote($$BASEDIR/../src/nm/net/*.c) \
        $$quote($$BASEDIR/../src/nm/net/*.c++) \
        $$quote($$BASEDIR/../src/nm/net/*.cc) \
        $$quote($$BASEDIR/../src/nm/net/*.cpp) \
        $$quote($$BASEDIR/../src/nm/net/*.cxx) \
        $$quote($$BASEDIR/../src/nm/session/*.c) \
        $$quote($$BASEDIR/../src/nm/session/*.c++) \
        $$quote($$BASEDIR/../src/nm/session/*.cc) \
        $$quote($$BASEDIR/../src/nm/session/*.cpp) \
        $$quote($$BASEDIR/../src/nm/session/*.cxx) \
        $$quote($$BASEDIR/../src/nm/util/*.c) \
        $$quote($$BASEDIR/../src/nm/util/*.c++) \
        $$quote($$BASEDIR/../src/nm/util/*.cc) \
        $$quote($$BASEDIR/../src/nm/util/*.cpp) \
        $$quote($$BASEDIR/../src/nm/util/*.cxx) \
        $$quote($$BASEDIR/../src/nm/util/qrcodegen/*.c) \
        $$quote($$BASEDIR/../src/nm/util/qrcodegen/*.c++) \
        $$quote($$BASEDIR/../src/nm/util/qrcodegen/*.cc) \
        $$quote($$BASEDIR/../src/nm/util/qrcodegen/*.cpp) \
        $$quote($$BASEDIR/../src/nm/util/qrcodegen/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/1440x1440/*.qml) \
        $$quote($$BASEDIR/../assets/1440x1440/*.js) \
        $$quote($$BASEDIR/../assets/1440x1440/*.qs) \
        $$quote($$BASEDIR/../assets/720x720/*.qml) \
        $$quote($$BASEDIR/../assets/720x720/*.js) \
        $$quote($$BASEDIR/../assets/720x720/*.qs) \
        $$quote($$BASEDIR/../assets/icons/*.qml) \
        $$quote($$BASEDIR/../assets/icons/*.js) \
        $$quote($$BASEDIR/../assets/icons/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
